# |--------------------------------------------------------------------------
# | Up tasks
# |--------------------------------------------------------------------------
# |
# | This file describes the up tasks of your project.
# | Feel free to add your own tasks!
# |
# | https://github.com/gulien/orbit/
# |

tasks:

  # |--------------------------------------------------------------------------
  # | orbit run docker-sync-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts Docker Sync.
  # |

  - use: docker-sync-up
    run:
      {{ if eq "true" .Orbit.EnvFile.ENABLE_DOCKER_SYNC }}
      - docker-sync start
      {{ else }}
      - echo Skipping Docker Sync startup ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run traefik-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the Traefik container.
  # |
  # | It should be the first to start.
  # |

  - use: traefik-up
    run:
      - docker-compose -p kickoff -f modules/traefik/docker-compose.yml up -d

  # |--------------------------------------------------------------------------
  # | orbit run graylog-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the Graylog containers.
  # |
  # | They should be start after the Traefik container.
  # |

  - use: graylog-up
    run:
      {{ if eq true .Orbit.Modules.graylog.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/graylog/docker-compose.yml up -d
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh Graylog graylog-server 9000"
      {{ else }}
      - echo Skipping Graylog containers startup ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run php-fpm-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the PHP-FPM container.
  # |
  # | It should be start after the Graylog containers.
  # |

  - use: php-fpm-up
    run:
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/php-fpm/docker-compose.yml up -d
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh PHP-FPM php-fpm 9000"


  # |--------------------------------------------------------------------------
  # | orbit run nginx-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the NGINX container.
  # |
  # | It should be start after the Graylog and PHP-FPM containers.
  # |

  - use: nginx-up
    run:
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/nginx/docker-compose.yml up -d
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh NGINX nginx 80"

  # |--------------------------------------------------------------------------
  # | orbit run mysql-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the MySQL container.
  # |
  # | On "local" environment, also starts the phpMyAdmin container.
  # |
  # | They should be start after the Graylog containers.
  # |

  - use: mysql-up
    run:
      {{ if eq true .Orbit.Modules.mysql.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/mysql/docker-compose.yml up -d
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh MySQL mysql 3306"
      {{ if eq "local" .Orbit.EnvFile.ENV }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh phpMyAdmin phpmyadmin 80"
      {{ end }}
      {{ else }}
      - echo Skipping MySQL container startup ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run mongodb-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the MongoDB container.
  # |
  # | On "local" environment, also starts the Mongo Express container.
  # |
  # | They should be start after the Graylog containers.
  # |

  - use: mongodb-up
    run:
      {{ if eq true .Orbit.Modules.mongodb.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/mongodb/docker-compose.yml up -d
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh MongoDB mongodb 27017"
      {{ if eq "local" .Orbit.EnvFile.ENV }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh MongoExpress mongodb-express 8081"
      {{ end }}
      {{ else }}
      - echo Skipping MongoDB container startup ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run neo4j-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the Neo4J container.
  # |
  # | They should be start after the Graylog containers.
  # |

  - use: neo4j-up
    run:
      {{ if eq true .Orbit.Modules.neo4j.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/neo4j/docker-compose.yml up -d
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh Neo4J neo4j 7474"
      {{ else }}
      - echo Skipping Neo4J container startup ...
      {{ end }}




  # |--------------------------------------------------------------------------
  # | orbit run redis-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the Redis container.
  # |
  # | It should be start after the Graylog containers.
  # |

  - use: redis-up
    run:
      {{ if eq true .Orbit.Modules.redis.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/redis/docker-compose.yml up -d
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh Redis redis 6379"
      {{ else }}
      - echo Skipping Redis container startup ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run rabbitmq-up
  # |--------------------------------------------------------------------------
  # |
  # | Starts the RabbitMQ container.
  # |
  # | It should be start after the Graylog containers.
  # |

  - use: rabbitmq-up
    run:
      {{ if eq true .Orbit.Modules.rabbitmq.enable }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/rabbitmq/docker-compose.yml up -d
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c "/scripts/health-check.sh RabbitMQ rabbitmq 15672"
      {{ else }}
      - echo Skipping RabbitMQ container startup ...
      {{ end }}