# |--------------------------------------------------------------------------
# | Build tasks
# |--------------------------------------------------------------------------
# |
# | This file describes the build tasks of your project.
# | Feel free to add your own tasks!
# |
# | https://github.com/gulien/orbit/
# |

tasks:

  # |--------------------------------------------------------------------------
  # | orbit run docker-sync-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates Docker Sync configuration file.
  # |

  - use: docker-sync-build
    run:
      {{ if eq "true" .Orbit.EnvFile.ENABLE_DOCKER_SYNC }}
      - orbit generate -f docker-sync.blueprint.yml -o docker-sync.yml {{ if debug }}-d{{ end }}
      - orbit run script-fix-permissions-docker-sync -f config/orbit/orbit-scripts.yml {{ if debug }}-d{{ end }}
      {{ else }}
      - echo Skipping Docker Sync configuration file generation ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run toolbox-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates Toolbox configuration files.
  # |

  - use: toolbox-build
    run:
      - orbit generate -f modules/toolbox/docker-compose.blueprint.yml -o modules/toolbox/docker-compose.yml {{ if debug }}-d{{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run traefik-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates Traefik configuration files.
  # |

  - use: traefik-build
    run:
      - orbit run script-traefik-self-signed-certificate -f config/orbit/orbit-scripts.yml {{ if debug }}-d{{ end }}
      - orbit run script-traefik-htdigest -f config/orbit/orbit-scripts.yml {{ if debug }}-d{{ end }}
      - orbit generate -f modules/traefik/traefik.blueprint.toml -o modules/traefik/traefik.toml {{ if debug }}-d{{ end }}
      - orbit generate -f modules/traefik/docker-compose.blueprint.yml -o modules/traefik/docker-compose.yml {{ if debug }}-d{{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run graylog-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates Graylog configuration files.
  # |

  - use: graylog-build
    run:
      {{ if eq true .Orbit.Modules.graylog.enable }}
      - orbit generate -f modules/graylog/docker-compose.blueprint.yml -o modules/graylog/docker-compose.yml {{ if debug }}-d{{ end }}
      - orbit generate -f modules/graylog/udp-input.blueprint.json -o modules/graylog/udp-input.json {{ if debug }}-d{{ end }}
      - orbit run script-graylog-secrets -f config/orbit/orbit-scripts.yml {{ if debug }}-d{{ end }}
      {{ else }}
      - echo Skipping Graylog configuration files generation ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run php-fpm-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates PHP-FPM configuration files.
  # |

  - use: php-fpm-build
    run:
      - orbit generate -f modules/php-fpm/docker-compose.blueprint.yml -o modules/php-fpm/docker-compose.yml {{ if debug }}-d{{ end }}
      - orbit run script-fix-permissions-php-fpm -f config/orbit/orbit-scripts.yml {{ if debug }}-d{{ end }}
      - orbit generate -f modules/php-fpm/conf.d/memory-limit.blueprint.ini -o modules/php-fpm/conf.d/memory-limit.ini {{ if debug }}-d{{ end }}
      - orbit generate -f modules/php-fpm/php-fpm.d/memory-limit.blueprint.conf -o modules/php-fpm/php-fpm.d/memory-limit.conf {{ if debug }}-d{{ end }}
      - orbit generate -f modules/php-fpm/php-fpm.d/security.blueprint.conf -o modules/php-fpm/php-fpm.d/security.conf {{ if debug }}-d{{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run nginx-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates NGINX configuration files and builds the image.
  # |

  - use: nginx-build
    run:
      - orbit generate -f modules/nginx/conf.d/php-fpm.blueprint.conf -o modules/nginx/conf.d/php-fpm.conf {{ if debug }}-d{{ end }}
      - orbit generate -f modules/nginx/docker-compose.blueprint.yml -o modules/nginx/docker-compose.yml {{ if debug }}-d{{ end }}
      - orbit run script-fix-permissions-nginx -f config/orbit/orbit-scripts.yml {{ if debug }}-d{{ end }}
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/nginx/docker-compose.yml build

  # |--------------------------------------------------------------------------
  # | orbit run mongo-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates Mongo configuration files.
  # |

  - use: mongodb-build
    run:
      {{ if eq true .Orbit.Modules.mongodb.enable }}
      - orbit generate -f modules/mongodb/docker-compose.blueprint.yml -o modules/mongodb/docker-compose.yml {{ if debug }}-d{{ end }}
      - orbit generate -f modules/mongodb/secrets/mongodb_root_password.blueprint.txt -o modules/mongodb/secrets/mongodb_root_password.txt {{ if debug }}-d{{ end }}
      {{ else }}
      - echo Skipping MongoDB configuration files generation ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run mysql-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates MySQL configuration files.
  # |

  - use: mysql-build
    run:
      {{ if eq true .Orbit.Modules.mysql.enable }}
      - orbit generate -f modules/mysql/docker-compose.blueprint.yml -o modules/mysql/docker-compose.yml {{ if debug }}-d{{ end }}
      - orbit generate -f modules/mysql/docker-entrypoint-initdb.d/databases.blueprint.sql -o modules/mysql/docker-entrypoint-initdb.d/databases.sql {{ if debug }}-d{{ end }}
      - orbit generate -f modules/mysql/secrets/mysql_password.blueprint.txt -o modules/mysql/secrets/mysql_password.txt {{ if debug }}-d{{ end }}
      - orbit generate -f modules/mysql/secrets/mysql_root_password.blueprint.txt -o modules/mysql/secrets/mysql_root_password.txt {{ if debug }}-d{{ end }}
      {{ else }}
      - echo Skipping MySQL configuration files generation ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run neo4j-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates Neo4J configuration files.
  # |

  - use: neo4j-build
    run:
      {{ if eq true .Orbit.Modules.neo4j.enable }}
      - orbit generate -f modules/neo4j/docker-compose.blueprint.yml -o modules/neo4j/docker-compose.yml {{ if debug }}-d{{ end }}
      {{ else }}
      - echo Skipping Neo4J configuration files generation ...
      {{ end }}
  # |--------------------------------------------------------------------------
  # | orbit run redis-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates Redis configuration files.
  # |

  - use: redis-build
    run:
      {{ if eq true .Orbit.Modules.redis.enable }}
      - orbit generate -f modules/redis/docker-compose.blueprint.yml -o modules/redis/docker-compose.yml {{ if debug }}-d{{ end }}
      {{ else }}
      - echo Skipping Redis configuration files generation ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run rabbitmq-build
  # |--------------------------------------------------------------------------
  # |
  # | Generates RabbitMQ configuration files.
  # |

  - use: rabbitmq-build
    run:
      {{ if eq true .Orbit.Modules.rabbitmq.enable }}
      - orbit generate -f modules/rabbitmq/docker-compose.blueprint.yml -o modules/rabbitmq/docker-compose.yml {{ if debug }}-d{{ end }}
      {{ else }}
      - echo Skipping RabbitMQ configuration files generation ...
      {{ end }}