traefik:

  # |--------------------------------------------------------------------------
  # | Traefik user
  # |--------------------------------------------------------------------------
  # |
  # | The Traefik user used for generating the .htdigest file.
  # |
  # | Only required for environments <> "local".
  # |

  user: kickoff

graylog:

  # |--------------------------------------------------------------------------
  # | Enable Graylog
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables Graylog.
  # |

  enable: false

  # |--------------------------------------------------------------------------
  # | Graylog user
  # |--------------------------------------------------------------------------
  # |
  # | The Graylog root user.
  # |

  user: kickoff

mongodb:

  # |--------------------------------------------------------------------------
  # | Enable MongoDB
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables MongoDB and makes sure support module is present in PHP.
  # |

  enable: false

  # |--------------------------------------------------------------------------
  # | Mongo Version
  # |--------------------------------------------------------------------------
  # |
  # | Determine which tag from Docker Hub to use
  # |
  version: 3

  user: kickoff

mysql:

  # |--------------------------------------------------------------------------
  # | Enable MySQL
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables MySQL.
  # |

  enable: true

  # |--------------------------------------------------------------------------
  # | MySQL user
  # |--------------------------------------------------------------------------
  # |
  # | The MySQL user of your PHP application.
  # |

  user: kickoff

  # |--------------------------------------------------------------------------
  # | MySQL databases
  # |--------------------------------------------------------------------------
  # |
  # | List of the databases of your PHP application. If they do not exist,
  # | they will be created when the MySQL container starts.
  # |
  # | The previous user will have all privileges on these databases.
  # |

  databases:
    - symfony

neo4j:

  # |--------------------------------------------------------------------------
  # | Enable Neo4J
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables Neo4J.
  # |

  enable: true

  # |--------------------------------------------------------------------------
  # | Neo4J Version
  # |--------------------------------------------------------------------------
  # |
  # | Determine which tag from Docker Hub to use
  # |
  version: 3.4

redis:

  # |--------------------------------------------------------------------------
  # | Enable Redis
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables Redis.
  # |

  enable: false

rabbitmq:

  # |--------------------------------------------------------------------------
  # | Enable RabbitMQ
  # |--------------------------------------------------------------------------
  # |
  # | If true, enables RabbitMQ.
  # |

  enable: false

  # |--------------------------------------------------------------------------
  # | RabbitMQ user
  # |--------------------------------------------------------------------------
  # |
  # | The RabbitMQ user of your PHP application.
  # |

  user: kickoff
